name: Docs
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependecies
        run: |
          pip install --upgrade pip
          pip install tox ghp-import

      - name: Build docs
        run: tox -e docs

      - name: Run ghp-import
        run: |
          git config user.name ABD-01
          git config user.email 63636498+ABD-01@users.noreply.github.com
          ghp-import -n -p -f -o docs/build