name: Documentation
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependecies
        run: |
          pip install --upgrade pip
          pip install tox ghp-import

      - name: Build docs
        run: tox -e docs

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f -o docs/build