name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey @${{ github.actor }}! Thanks for creating this issue. Please wait while the maintainers review your issue."
        pr-message: "Hey @${{ github.actor }}! Thanks for your contribution. Please wait while the maintainers review your PR"
  